# Generated by Django 3.2.5 on 2021-07-16 10:49

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bridal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=150)),
                ('sub_title', models.CharField(max_length=150)),
                ('design', models.CharField(max_length=150)),
                ('purpose', models.CharField(max_length=150)),
                ('aouther_name', models.CharField(max_length=150)),
                ('description', ckeditor.fields.RichTextField()),
                ('photo', models.ImageField(blank=True, upload_to='photos/%y/%m/%d/')),
                ('photo1', models.ImageField(blank=True, upload_to='photos/%y/%m/%d/')),
                ('photo2', models.ImageField(blank=True, upload_to='photos/%y/%m/%d/')),
                ('photo3', models.ImageField(blank=True, upload_to='photos/%y/%m/%d/')),
                ('photo4', models.ImageField(blank=True, upload_to='photos/%y/%m/%d/')),
                ('photo5', models.ImageField(blank=True, upload_to='photos/%y/%m/%d/')),
                ('photo6', models.ImageField(blank=True, upload_to='photos/%y/%m/%d/')),
                ('photo7', models.ImageField(blank=True, upload_to='photos/%y/%m/%d/')),
                ('photo8', models.ImageField(blank=True, upload_to='photos/%y/%m/%d/')),
                ('photo9', models.ImageField(blank=True, upload_to='photos/%y/%m/%d/')),
                ('photo10', models.ImageField(blank=True, upload_to='photos/%y/%m/%d/')),
                ('photo11', models.ImageField(blank=True, upload_to='photos/%y/%m/%d/')),
                ('cost', models.IntegerField()),
                ('service_place', models.CharField(max_length=150)),
                ('serial_no', models.IntegerField()),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
